### ISSUE TITLE
cannot connect to HA behind reverse proxy with cert signed by my own CA

### ISSUE THREAD

**Issue by thatso** [LaTrappe/HAKA#11]
**Describe the bug**
HAKA cannot connect to HA behind a reverse proxy with a certificate signed by my own CA.

**To Reproduce**
I run Home Assistant behind Nginx reverse proxy with a self-signed certificate trusted by my own CA (LAN only, not publically accessible).
I've added the CA to LibreELEC's certificate store as explained [here](https://forum.libreelec.tv/thread/20753-how-do-i-add-additional-certificate-authorities-for-mitm-proxy-such-as-burp-mitm/).
This works with _curl_. Relevant output in SSH:

```
# curl --verbose https://<myhomeassistanturl>
*   Trying x.x.x.x:443...
* Connected to <myhomeassistanturl> (x.x.x.x) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /run/libreelec/cacert.pem
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=<myhomeassistanturl>
*  start date: <some date in the past>
*  expire date: <some date in the future>
*  subjectAltName: host "xxxxx" matched cert's "xxxxx"
*  issuer: C=xx; O=xxxxx; OU=CA
*  **SSL certificate verify ok.**   <==================================================
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0xcfefc0)
> GET / HTTP/2
> Host: <myhomeassistanturl>
> user-agent: curl/7.74.0
> accept: */*
> referer: rbose
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 200 
< server: nginx [...]
```

However, HAKA fails to connect with these entries in the Kodi log:

```
EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'UnboundLocalError'>
                                                   Error Contents: local variable 'r' referenced before assignment
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 699, in urlopen
                                                       httplib_response = self._make_request(
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 382, in _make_request
                                                       self._validate_conn(conn)
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 1010, in _validate_conn
                                                       conn.connect()
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connection.py", line 411, in connect
                                                       self.sock = ssl_wrap_socket(
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
                                                       ssl_sock = _ssl_wrap_socket_impl(
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
                                                       return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
                                                     File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
                                                     File "/usr/lib/python3.8/ssl.py", line 1040, in _create
                                                     File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
                                                   ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 439, in send
                                                       resp = conn.urlopen(
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 755, in urlopen
                                                       retries = retries.increment(
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/util/retry.py", line 574, in increment
                                                       raise MaxRetryError(_pool, url, error or ResponseError(cause))
                                                   urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='<myhomeassistanturl>', port=443): Max retries exceeded with url: //api/config (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)')))
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.program.homeassistant/addon.py", line 128, in getRequest
                                                       r = requests.get(api_base + api_ext, headers=headers)
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/api.py", line 76, in get
                                                       return request('get', url, params=params, **kwargs)
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/api.py", line 61, in request
                                                       return session.request(method=method, url=url, **kwargs)
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 542, in request
                                                       resp = self.send(prep, **send_kwargs)
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 655, in send
                                                       r = adapter.send(request, **kwargs)
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 514, in send
                                                       raise SSLError(e, request=request)
                                                   requests.exceptions.SSLError: HTTPSConnectionPool(host='<myhomeassistanturl>', port=443): Max retries exceeded with url: //api/config (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)')))
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.program.homeassistant/addon.py", line 376, in <module>
                                                       browseByDomain()
                                                     File "/storage/.kodi/addons/script.program.homeassistant/addon.py", line 162, in browseByDomain
                                                       response = getRequest('/config')
                                                     File "/storage/.kodi/addons/script.program.homeassistant/addon.py", line 132, in getRequest
                                                       log('Status code error is: ' + str(r.raise_for_status()))
                                                   UnboundLocalError: local variable 'r' referenced before assignment
                                                   -->End of Python script error report<--
```

**Expected behavior**
Regarding the line
`[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate`
it seems that _urllib3_ does not respect my own CA certificate or something like that?

**Desktop:**
 - OS: LibreELEC 10.0.0 RPi4.arm
 - Kodi version 19.1.0
 - Home Assistant installation description: Home Assistant OS 6.4, core-2021.9.6 behind Nginx reverse proxy
 - HAKA version: 1.1.0

**Comment by LaTrappe** [comment]
To be honest. I have no clue. I advice you to drop this question either at the urlib3 maintainer or create a direct line from Kodi to HA. If you know more and if there's anything to fix in the code, let me know or reopen the issue.
