### ISSUE TITLE
HAKA will not connect to Hass.

### ISSUE THREAD

**Issue by zang74** [LaTrappe/HAKA#14]
**Describe the bug**
HAKA plugin will not run. Installs and activates, but will not retrieve info from HASS server.

**To Reproduce**
?

**Expected behavior**
I expected it to connect to the server.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu Mate 22.04 Jammy on Intel J4105 based machine
 - Kodi version 19.4
 - Home Assistant installation description: Home Assistant 2022.3.3 running on HassOS 7.4
 - HAKA version: 1.2.0

**Additional context**
Logging specific to the plugin:

2022-03-11 12:41:43.813 T:2531401    INFO <general>: initializing python engine.
2022-03-11 12:41:44.995 T:2531401   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'UnboundLocalError'>
                                                   Error Contents: local variable 'r' referenced before assignment
                                                   Traceback (most recent call last):
                                                     File "/home/superuser/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 703, in urlopen
                                                       httplib_response = self._make_request(
                                                     File "/home/superuser/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 386, in _make_request
                                                       self._validate_conn(conn)
                                                     File "/home/superuser/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 1040, in _validate_conn
                                                       conn.connect()
                                                     File "/home/superuser/.kodi/addons/script.module.urllib3/lib/urllib3/connection.py", line 416, in connect
                                                       self.sock = ssl_wrap_socket(
                                                     File "/home/superuser/.kodi/addons/script.module.urllib3/lib/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
                                                       ssl_sock = _ssl_wrap_socket_impl(
                                                     File "/home/superuser/.kodi/addons/script.module.urllib3/lib/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
                                                       return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
                                                     File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
                                                       return self.sslsocket_class._create(
                                                     File "/usr/lib/python3.9/ssl.py", line 1040, in _create
                                                       self.do_handshake()
                                                     File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
                                                       self._sslobj.do_handshake()
                                                   ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)

                                                   During handling of the above exception, another exception occurred:

                                                   Traceback (most recent call last):
                                                     File "/home/superuser/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 439, in send
                                                       resp = conn.urlopen(
                                                     File "/home/superuser/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 785, in urlopen
                                                       retries = retries.increment(
                                                     File "/home/superuser/.kodi/addons/script.module.urllib3/lib/urllib3/util/retry.py", line 592, in increment
                                                       raise MaxRetryError(_pool, url, error or ResponseError(cause))
                                                   urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='itsasecret.duckdns.org', port=8123): Max retries exceeded with url: /api/config (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)')))

                                                   During handling of the above exception, another exception occurred:

                                                   Traceback (most recent call last):
                                                     File "/home/superuser/.kodi/addons/script.program.homeassistant/addon.py", line 132, in getRequest
                                                       r = requests.get(api_base + api_ext, headers=headers)
                                                     File "/home/superuser/.kodi/addons/script.module.requests/lib/requests/api.py", line 76, in get
                                                       return request('get', url, params=params, **kwargs)
                                                     File "/home/superuser/.kodi/addons/script.module.requests/lib/requests/api.py", line 61, in request
                                                       return session.request(method=method, url=url, **kwargs)
                                                     File "/home/superuser/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 542, in request
                                                       resp = self.send(prep, **send_kwargs)
                                                     File "/home/superuser/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 655, in send
                                                       r = adapter.send(request, **kwargs)
                                                     File "/home/superuser/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 514, in send
                                                       raise SSLError(e, request=request)
                                                   requests.exceptions.SSLError: HTTPSConnectionPool(host='itsasecret.duckdns.org', port=8123): Max retries exceeded with url: /api/config (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)')))

                                                   During handling of the above exception, another exception occurred:

                                                   Traceback (most recent call last):
                                                     File "/home/superuser/.kodi/addons/script.program.homeassistant/addon.py", line 381, in <module>
                                                       browseByDomain()
                                                     File "/home/superuser/.kodi/addons/script.program.homeassistant/addon.py", line 166, in browseByDomain
                                                       response = getRequest('/config')
                                                     File "/home/superuser/.kodi/addons/script.program.homeassistant/addon.py", line 136, in getRequest
                                                       log('Status code error is: ' + str(r.raise_for_status()))
                                                   UnboundLocalError: local variable 'r' referenced before assignment
                                                   -->End of Python script error report<--

2022-03-11 12:41:45.054 T:2531401    INFO <general>: Python interpreter stopped
2022-03-11 12:41:45.070 T:2531400   ERROR <general>: GetDirectory - Error getting plugin://script.program.homeassistant/
2022-03-11 12:41:45.113 T:2489747   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://script.program.homeassistant/) failed

**Comment by LaTrappe** [comment]
Hi, I see you are using the external URL of HA to connect to and the issue is in the SSL side of things. Does the same thing happens when using the local/internal URL of HA? Why do you even need or want to connect to the external URL?

**Comment by zang74** [comment]
Yep. Same message. At first I thought it was because I was using a non-standard external forwarding port (I changed it in logs for security reasons), but the same applies to homeassistant.local:8123

There was no particular reason for the external being used, it just happened that I grabbed the log from that attempt, rather than the first using the above local address.

**Comment by LaTrappe** [comment]
I think I need a little bit more info:

- Is your HA installation running on HTTPS / SSL?
- Or do you use a reverse proxy in between?
- Did you put either HTTP:// or HTTPS:// in front of the URL?

**Comment by zang74** [comment]
I run NGINX as a reverse proxy on my HASS install. You're right, I was (stupidly) using https: on my .local address. I checked and it does work if I go the non-SSL route locally.

Though for security reasons, why not support alternative external forwarding ports? It certainly doesn't hurt.

**Comment by LaTrappe** [comment]
This is perfectly possible. Are you sure you did use the right external URL?
