### ISSUE TITLE
Unknown error: Check IP address or if server is online 

### ISSUE THREAD

**Issue by nocturneop15** [LaTrappe/HAKA#2]
After initial setup, I'm getting "Unknown error: Check IP address or if server is online " message. 

Env: 
  - Coreelec 9.2.5/Kodi 18.9
  - Home Assistant Core 0.117.5,  api enabled 
  - API url available from network, from browser getting .401 Unauthorized accessing "https://192.168.58.7:8123/api/config"
  - !! Homeassistant has my own CA signed certificate, which is not publicly trusted !!
  - tried with both DNS and IP address, result is the same 

 
Debug log enabled, tail: 

CoreELEC:~/.kodi/temp # tail kodi.log
                                                parsedResponse = json.loads(response.text)
                                            AttributeError: 'NoneType' object has no attribute 'text'
                                            -->End of Python script error report<--
2020-11-12 23:23:30.331 T:3605140352   ERROR: GetDirectory - Error getting plugin://script.program.homassistant/
2020-11-12 23:23:30.332 T:4060181072   ERROR: CGUIMediaWindow::GetDirectory(plugin://script.program.homassistant/) failed
2020-11-12 23:27:03.367 T:4060181072   ERROR: Control 55 in window 10001 has been asked to focus, but it can't
2020-11-12 23:27:03.932 T:3514020736  NOTICE: script.program.homassistant: HAKA Started
2020-11-12 23:27:03.932 T:3514020736  NOTICE: script.program.homassistant: Domain settings imported: [False, False, False, False, False, False, True, False, False]
2020-11-12 23:27:03.932 T:3514020736  NOTICE: script.program.homassistant: Browse by domain started
2020-11-12 23:27:03.941 T:3514020736  NOTICE: script.program.homassistant: Trying to make a get request to https://192.168.58.7:8123/api/config

Can I somehow help to debug this? I suspect non-trusted cert could be the issue...

**Comment by LaTrappe** [comment]
Hi @nocturneop15 
Are you sure this is the end of the log file? I was hoping it would also get to the stage where its logs the status code of the response. 

I did not test it with an own certificate. 

Cheers

**Comment by nocturneop15** [comment]
Hi, LaTrappe, 
I made completely fresh log, you are true - it contains much more information, I'm not sure why i got incomplete output from tail for the first time. Here is full log: 

```
2020-11-16 23:03:17.210 T:3653915520  NOTICE: script.program.homassistant: HAKA Started
2020-11-16 23:03:17.211 T:3653915520  NOTICE: script.program.homassistant: Domain settings imported: [False, False, False, False, False, False, True, False, False]
2020-11-16 23:03:17.211 T:3653915520  NOTICE: script.program.homassistant: Browse by domain started
2020-11-16 23:03:17.219 T:3653915520  NOTICE: script.program.homassistant: Trying to make a get request to https://192.168.58.7:8123/api/config
2020-11-16 23:03:20.517 T:3653915520  NOTICE: script.program.homassistant: Response from server is NONE!
2020-11-16 23:03:20.522 T:3653915520   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'text'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.program.homassistant/addon.py", line 261, in <module>
                                                browseByDomain()
                                              File "/storage/.kodi/addons/script.program.homassistant/addon.py", line 147, in browseByDomain
                                                parsedResponse = json.loads(response.text)
                                            AttributeError: 'NoneType' object has no attribute 'text'
                                            -->End of Python script error report<--
2020-11-16 23:03:20.634 T:3943674752   ERROR: GetDirectory - Error getting plugin://script.program.homassistant/
2020-11-16 23:03:20.635 T:4064375376   ERROR: CGUIMediaWindow::GetDirectory(plugin://script.program.homassistant/) failed
```

**Comment by LaTrappe** [comment]
Hi,

I've changed the logging a bit. Its not gonna solve your issue, but hopefully gives us a bit more insight. Please download and install from https://github.com/LaTrappe/HAKA/tree/LaTrappe-patch-1 and feedback the logs. Thanks

**Comment by nocturneop15** [comment]
This patch does not throw error message window, but still exception is logged: 

```
2020-11-17 22:00:57.932 T:4063064656   ERROR: CGUIMediaWindow::GetDirectory(plugin://script.program.homassistant/) failed
2020-11-17 22:01:03.934 T:3480339328  NOTICE: script.program.homassistant: HAKA Started
2020-11-17 22:01:03.934 T:3480339328  NOTICE: script.program.homassistant: Domain settings imported: [False, False, False, False, False, False, True, False, False]
2020-11-17 22:01:03.934 T:3480339328  NOTICE: script.program.homassistant: Browse by domain started
2020-11-17 22:01:03.967 T:3480339328  NOTICE: script.program.homassistant: Trying to make a get request to https://192.168.58.7:8123/api/config
2020-11-17 22:01:04.032 T:3480339328   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'r' referenced before assignment
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.program.homassistant/addon.py", line 262, in <module>
                                                browseByDomain()
                                              File "/storage/.kodi/addons/script.program.homassistant/addon.py", line 143, in browseByDomain
                                                response = getRequest('/config')
                                              File "/storage/.kodi/addons/script.program.homassistant/addon.py", line 113, in getRequest
                                                log('Status code error is: ' + str(r.raise_for_status()))
                                            UnboundLocalError: local variable 'r' referenced before assignment
                                            -->End of Python script error report<--
2020-11-17 22:01:04.170 T:3368031104   ERROR: GetDirectory - Error getting plugin://script.program.homassistant/
2020-11-17 22:01:04.199 T:4063064656   ERROR: CGUIMediaWindow::GetDirectory(plugin://script.program.homassistant/) failed
```

**Comment by nocturneop15** [comment]
I will try to get my root CA trusted in coreelec, i still suspect this might an issue. A friend of mine, who does not use HTTPS for HA, does not have this issue
